"""add codigo recuperacao ao usuario

Revision ID: 70055d0afa2d
Revises: eb5e03a7f1b2
Create Date: 2026-08-31 20:41:40.055015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '70055d0afa2d'
down_revision: Union[str, Sequence[str], None] = 'eb5e03a7f1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('codigo_recuperacao', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=True))
    op.add_column('usuario', sa.Column('codigo_recuperacao_expira', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'codigo_recuperacao_expira')
    op.drop_column('usuario', 'codigo_recuperacao')
    # ### end Alembic commands ###
