"""acrescimo do campo de data

Revision ID: b1f202e46c5c
Revises: 18e655701ec2
Create Date: 2026-07-26 18:01:20.161952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1f202e46c5c'
down_revision: Union[str, Sequence[str], None] = '18e655701ec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movimentações', sa.Column('data_movimentacao', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movimentações', 'data_movimentacao')
    # ### end Alembic commands ###
