"""cria tabelas atualizadas

Revision ID: c46340f0ba4f
Revises: 
Create Date: 2026-08-06 23:33:55.012974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c46340f0ba4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('senha', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('emailrec', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=False)
    op.create_index(op.f('ix_usuario_nome'), 'usuario', ['nome'], unique=False)
    op.create_table('agenda',
    sa.Column('id_agenda', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'concluida', 'atrasada', name='statusagenda'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_agenda')
    )
    op.create_index(op.f('ix_agenda_id_usuario'), 'agenda', ['id_usuario'], unique=False)
    op.create_table('financeiro',
    sa.Column('id_financeiro', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_financeiro')
    )
    op.create_index(op.f('ix_financeiro_id_usuario'), 'financeiro', ['id_usuario'], unique=False)
    op.create_table('transacao',
    sa.Column('id_transacoes', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_financeiro', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('tipo', sa.Enum('entrada', 'saida', name='tipotransacao'), nullable=False),
    sa.Column('data_mov', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_financeiro'], ['financeiro.id_financeiro'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_transacoes')
    )
    op.create_index(op.f('ix_transacao_id_financeiro'), 'transacao', ['id_financeiro'], unique=False)
    op.create_index(op.f('ix_transacao_id_usuario'), 'transacao', ['id_usuario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transacao_id_usuario'), table_name='transacao')
    op.drop_index(op.f('ix_transacao_id_financeiro'), table_name='transacao')
    op.drop_table('transacao')
    op.drop_index(op.f('ix_financeiro_id_usuario'), table_name='financeiro')
    op.drop_table('financeiro')
    op.drop_index(op.f('ix_agenda_id_usuario'), table_name='agenda')
    op.drop_table('agenda')
    op.drop_index(op.f('ix_usuario_nome'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###
