"""add campo deleted_temp na tabela Agenda

Revision ID: c7874283d8e2
Revises: 109ea34563a6
Create Date: 2026-09-24 20:37:46.854674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7874283d8e2'
down_revision: Union[str, Sequence[str], None] = '109ea34563a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agenda', sa.Column('deleted_temp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agenda', 'deleted_temp')
    # ### end Alembic commands ###
