"""criação do campo de rotina

Revision ID: e8a77c862017
Revises: b1f202e46c5c
Create Date: 2026-07-30 20:42:08.620898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8a77c862017'
down_revision: Union[str, Sequence[str], None] = 'b1f202e46c5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atividades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('atividade', sa.String(), nullable=True),
    sa.Column('usuario', sa.Integer(), nullable=True),
    sa.Column('conclusao', sa.DateTime(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atividades')
    # ### end Alembic commands ###
