"""add saldo em valores

Revision ID: eb5e03a7f1b2
Revises: 62d916c7c8dc
Create Date: 2026-08-27 21:58:55.401187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb5e03a7f1b2'
down_revision: Union[str, Sequence[str], None] = '62d916c7c8dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('valores', sa.Column('saldo', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('valores', 'saldo')
    # ### end Alembic commands ###
